if(NOT DEFINED TARGET_SYSTEM)
    message(FATAL_ERROR "TARGET_SYSTEM is not set. Please specify it before running CMake.")
endif()

if(${TARGET_SYSTEM} STREQUAL DockerLinux)
    message("Loading CMake project for Docker Linux")
    set(ENV_FILE_NAME docker-linux)
elseif(${TARGET_SYSTEM} STREQUAL Windows)
    message("Loading CMake project for Windows")
    cmake_policy(SET CMP0091 NEW)
    set(ENV_FILE_NAME windows)
elseif(${TARGET_SYSTEM} STREQUAL Linux)
    message("Loading CMake project for Linux")
    set(ENV_FILE_NAME linux)
elseif(${TARGET_SYSTEM} STREQUAL Conan)
    message("Loading CMake project for Conan")
    set(ENV_FILE_NAME conan)
else()
    message(FATAL_ERROR "Unsupported TARGET_SYSTEM: ${TARGET_SYSTEM}. Please specify a valid value.")
endif()

if (CMAKE_BUILD_TYPE STREQUAL "Release")
    set(CONAN_FOLDER_POSTFIX "RELEASE")
    set(CMAKE_CONAN_DEBUG_POSTFIX "")
else ()
    set(CONAN_FOLDER_POSTFIX "DEBUG")
    set(CMAKE_CONAN_DEBUG_POSTFIX "d")
endif ()

set(LIB_SHARED_LIBS ON)
include(envs/${ENV_FILE_NAME}.cmake)
include(${CMAKE_SOURCE_DIR}/deps/conan_toolchain.cmake)
